# 本地提示词管理软件 - 快捷键映射配置示例
# 此文件展示了如何配置快捷键映射到不同功能的提示词模板

hotkeys:
  # 文本处理相关快捷键
  ctrl+shift+1: tidy_content.md        # 内容整理
  ctrl+shift+2: translate.md           # 翻译功能

settings:
  # 启用快捷键监听
  enabled: true
  
  # 响应延迟设置（毫秒）
  response_delay: 100

# 实际使用示例:
# 
# 场景1: 内容整理
# 1. 选中需要整理的文本
# 2. 按下 Ctrl+Shift+1
# 3. AI会将文本进行整理和格式化
#
# 场景2: 翻译文本
# 1. 选中需要翻译的文本
# 2. 按下 Ctrl+Shift+2
# 3. AI会将文本插入翻译模板并返回翻译结果

# 模板文件命名建议:
# - 使用英文和下划线命名
# - 名称要能清楚表达功能
# - 保持简洁且易于理解 