hotkeys:
  ctrl+alt+cmd+1: template1.md
  ctrl+alt+cmd+2: template2.md
  ctrl+alt+cmd+3: template3.md
  ctrl+alt+cmd+4: template4.md
  ctrl+alt+cmd+5: template5.md
  ctrl+alt+cmd+6: template6.md
  ctrl+alt+cmd+7: template7.md
  ctrl+alt+cmd+8: template8.md
  ctrl+alt+cmd+9: template9.md
settings:
  enabled: true
  response_delay: 100
